
export const FETCH_LIST_BOOK = 'FETCH_LIST_BOOK'
export const FETCH_LIST_SUCCESS_BOOK = 'FETCH_LIST_SUCCESS_BOOK'
export const FETCH_LIST_ERROR_BOOK = 'FETCH_LIST_ERROR_BOOK'

export const FETCH_LIST_CATEGORY = 'FETCH_LIST_CATEGORY'
export const FETCH_LIST_SUCCESS_CATEGORY = 'FETCH_LIST_SUCCESS_CATEGORY'
export const FETCH_LIST_ERROR_CATEGORY = 'FETCH_LIST_ERROR_CATEGORY'

export const FETCH_LIST_AUTHOR = 'FETCH_LIST_AUTHOR'
export const FETCH_LIST_SUCCESS_AUTHOR = 'FETCH_LIST_SUCCESS_AUTHOR'
export const FETCH_LIST_ERROR_AUTHOR = 'FETCH_LIST_ERROR_AUTHOR'

export const FETCH_BOOK = 'FETCH_BOOK'
export const FETCH_SUCCESS_BOOK = 'FETCH_SUCCESS_BOOK'
export const FETCH_ERROR_BOOK = 'FETCH_ERROR_BOOK'

export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const FETCH_SUCCESS_CATEGORY = 'FETCH_SUCCESS_CATEGORY'
export const FETCH_ERROR_CATEGORY = 'FETCH_ERROR_CATEGORY'

export const FETCH_AUTHOR = 'FETCH_AUTHOR'
export const FETCH_SUCCESS_AUTHOR = 'FETCH_SUCCESS_AUTHOR'
export const FETCH_ERROR_AUTHOR = 'FETCH_ERROR_AUTHOR'

export const ADDEDIT_BOOK = 'ADDEDIT_BOOK'
export const ADDEDIT_SUCCESS_BOOK = 'ADDEDIT_SUCCESS_BOOK'
export const ADDEDIT_ERROR_BOOK = 'ADDEDIT_ERROR_BOOK'

export default {
    FETCH_LIST_BOOK,
    FETCH_LIST_SUCCESS_BOOK,
    FETCH_LIST_ERROR_BOOK,

    FETCH_LIST_CATEGORY,
    FETCH_LIST_SUCCESS_CATEGORY,
    FETCH_LIST_ERROR_CATEGORY,

    FETCH_LIST_AUTHOR,
    FETCH_LIST_SUCCESS_AUTHOR,
    FETCH_LIST_ERROR_AUTHOR,

    FETCH_BOOK,
    FETCH_SUCCESS_BOOK,
    FETCH_ERROR_BOOK,

    FETCH_CATEGORY,
    FETCH_SUCCESS_CATEGORY,
    FETCH_ERROR_CATEGORY,

    FETCH_AUTHOR,
    FETCH_SUCCESS_AUTHOR,
    FETCH_ERROR_AUTHOR,


    ADDEDIT_BOOK,
    ADDEDIT_SUCCESS_BOOK,
    ADDEDIT_ERROR_BOOK,
}