
export const FETCH_LIST_BOOK = 'FETCH_LIST_BOOK'
export const FETCH_LIST_SUCCESS_BOOK = 'FETCH_LIST_SUCCESS_BOOK'
export const FETCH_LIST_ERROR_BOOK = 'FETCH_LIST_ERROR_BOOK'

export const FETCH_LIST_CATEGORY = 'FETCH_LIST_CATEGORY'
export const FETCH_LIST_SUCCESS_CATEGORY = 'FETCH_LIST_SUCCESS_CATEGORY'
export const FETCH_LIST_ERROR_CATEGORY = 'FETCH_LIST_ERROR_CATEGORY'

export const FETCH_LIST_AUTHOR = 'FETCH_LIST_AUTHOR'
export const FETCH_LIST_SUCCESS_AUTHOR = 'FETCH_LIST_SUCCESS_AUTHOR'
export const FETCH_LIST_ERROR_AUTHOR = 'FETCH_LIST_ERROR_AUTHOR'

export const FETCH_BOOK = 'FETCH_BOOK'
export const FETCH_SUCCESS_BOOK = 'FETCH_SUCCESS_BOOK'
export const FETCH_ERROR_BOOK = 'FETCH_ERROR_BOOK'

export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const FETCH_SUCCESS_CATEGORY = 'FETCH_SUCCESS_CATEGORY'
export const FETCH_ERROR_CATEGORY = 'FETCH_ERROR_CATEGORY'

export const FETCH_AUTHOR = 'FETCH_AUTHOR'
export const FETCH_SUCCESS_AUTHOR = 'FETCH_SUCCESS_AUTHOR'
export const FETCH_ERROR_AUTHOR = 'FETCH_ERROR_AUTHOR'

export const ADD_BOOK = 'ADD_BOOK'
export const ADD_SUCCESS_BOOK = 'ADD_SUCCESS_BOOK'
export const ADD_ERROR_BOOK = 'ADD_ERROR_BOOK'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_SUCCESS_CATEGORY = 'ADD_SUCCESS_CATEGORY'
export const ADD_ERROR_CATEGORY = 'ADD_ERROR_CATEGORY'

export const ADD_AUTHOR = 'ADD_AUTHOR'
export const ADD_SUCCESS_AUTHOR = 'ADD_SUCCESS_AUTHOR'
export const ADD_ERROR_AUTHOR = 'ADD_ERROR_AUTHOR'

export const SET_EDIT_MODE = 'SET_EDIT_MODE'
export const GET_EDIT_MODE = 'GET_EDIT_MODE'

export const EDIT_BOOK = 'EDIT_BOOK'
export const EDIT_SUCCESS_BOOK = 'EDIT_SUCCESS_BOOK'
export const EDIT_ERROR_BOOK = 'EDIT_ERROR_BOOK'

export const EDIT_AUTHOR = 'EDIT_AUTHOR'
export const EDIT_SUCCESS_AUTHOR = 'EDIT_SUCCESS_AUTHOR'
export const EDIT_ERROR_AUTHOR = 'EDIT_ERROR_AUTHOR'

export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const EDIT_SUCCESS_CATEGORY = 'EDIT_SUCCESS_CATEGORY'
export const EDIT_ERROR_CATEGORY = 'EDIT_ERROR_CATEGORY'

export default {
    FETCH_LIST_BOOK,
    FETCH_LIST_SUCCESS_BOOK,
    FETCH_LIST_ERROR_BOOK,

    FETCH_LIST_CATEGORY,
    FETCH_LIST_SUCCESS_CATEGORY,
    FETCH_LIST_ERROR_CATEGORY,

    FETCH_LIST_AUTHOR,
    FETCH_LIST_SUCCESS_AUTHOR,
    FETCH_LIST_ERROR_AUTHOR,

    FETCH_BOOK,
    FETCH_SUCCESS_BOOK,
    FETCH_ERROR_BOOK,

    FETCH_CATEGORY,
    FETCH_SUCCESS_CATEGORY,
    FETCH_ERROR_CATEGORY,

    FETCH_AUTHOR,
    FETCH_SUCCESS_AUTHOR,
    FETCH_ERROR_AUTHOR,


    ADD_BOOK,
    ADD_SUCCESS_BOOK,
    ADD_ERROR_BOOK,

    EDIT_BOOK,
    EDIT_SUCCESS_BOOK,
    EDIT_ERROR_BOOK,

    ADD_AUTHOR,
    ADD_SUCCESS_AUTHOR,
    ADD_ERROR_AUTHOR,

    ADD_CATEGORY,
    ADD_SUCCESS_CATEGORY,
    ADD_ERROR_CATEGORY,


    EDIT_AUTHOR,
    EDIT_SUCCESS_AUTHOR,
    EDIT_ERROR_AUTHOR,

    EDIT_CATEGORY,
    EDIT_SUCCESS_CATEGORY,
    EDIT_ERROR_CATEGORY,

    SET_EDIT_MODE,
    GET_EDIT_MODE
}