
export const FETCH_LIST_BOOK = 'FETCH_LIST_BOOK'
export const FETCH_LIST_SUCCESS_BOOK = 'FETCH_LIST_SUCCESS_BOOK'
export const FETCH_LIST_ERROR_BOOK = 'FETCH_LIST_ERROR_BOOK'

export const FETCH_LIST_CATEGORY = 'FETCH_LIST_CATEGORY'
export const FETCH_LIST_SUCCESS_CATEGORY = 'FETCH_LIST_SUCCESS_CATEGORY'
export const FETCH_LIST_ERROR_CATEGORY = 'FETCH_LIST_ERROR_CATEGORY'

export const FETCH_LIST_AUTHOR = 'FETCH_LIST_AUTHOR'
export const FETCH_LIST_SUCCESS_AUTHOR = 'FETCH_LIST_SUCCESS_AUTHOR'
export const FETCH_LIST_ERROR_AUTHOR = 'FETCH_LIST_ERROR_AUTHOR'

export const SET_ITEM_DETAILS_BOOK = 'SET_ITEM_DETAILS_BOOK'
export const SET_ITEM_DETAILS_CATEGORY = 'SET_ITEM_DETAILS_CATEGORY'
export const SET_ITEM_DETAILS_AUTHOR = 'SET_ITEM_DETAILS_AUTHOR'

export default {
    FETCH_LIST_BOOK,
    FETCH_LIST_SUCCESS_BOOK,
    FETCH_LIST_ERROR_BOOK,

    FETCH_LIST_CATEGORY,
    FETCH_LIST_SUCCESS_CATEGORY,
    FETCH_LIST_ERROR_CATEGORY,

    FETCH_LIST_AUTHOR,
    FETCH_LIST_SUCCESS_AUTHOR,
    FETCH_LIST_ERROR_AUTHOR,

    SET_ITEM_DETAILS_BOOK,
    SET_ITEM_DETAILS_CATEGORY,
    SET_ITEM_DETAILS_AUTHOR

}